version: '3'

services:
  kinetik_telemetry_node_container:
    container_name: kinetik_telemetry_node_container
    build:
      context: ./kinetik_telemetry_node/
    volumes:
      - ./project_be:/var/www/project_be:delegated
    ports:
      - ${NODEJS_PORT}:3000
      - ${WS_PORT}:3001
    networks:
      - symnet
  kinetik_telemetry_react_container:
    container_name: kinetik_telemetry_react_container
    build:
      context: ./kinetik_telemetry_react/
    volumes:
      - ./project_fe:/var/www/project_fe:delegated
    ports:
      - ${REACT_PORT}:3000
    networks:
      - symnet
  kinetik_telemetry_db_container:
    container_name: kinetik_telemetry_db_container
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql:delegated
    networks:
      - symnet

networks:
  symnet:
    driver: bridge